language: minimal
dist: xenial

env:
  matrix:
    - PYTHON_VERSION=3.7

git:
  # We need a deep clone so that we can compute the age of the files using their git history.
  depth: 10000

branches:
  only:
    - gh-pages

install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE="http://repo.continuum.io/miniconda/Miniconda3"
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the testing environment
  # ------------------------------
  - conda config --set always_yes true
  - conda config --set changeps1 no
  - conda config --set show_channel_urls true
  - conda config --add channels conda-forge
  - ENV_NAME="test-environment"
  - conda create --quiet -n ${ENV_NAME} python=${PYTHON_VERSION}
  - source activate ${ENV_NAME}

  # Customise the testing environment
  # ---------------------------------
  - conda install --quiet --file conda-requirements.txt

  # Summerise environment
  # ---------------------
  - conda list
  - conda info -a

script: python run_test.py
