language: python

sudo: false

branches:
  only:
    - gh-pages

python:
  - "2.7"

git:
  depth: 10000

install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE="http://repo.continuum.io/miniconda/Miniconda2"
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the testing environment
  # ------------------------------
  - conda config --set always_yes true
  - conda config --set changeps1 no
  - conda config --set show_channel_urls true
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME="test-environment"
  - conda create --quiet -n ${ENV_NAME} python=${TRAVIS_PYTHON_VERSION}
  - source activate ${ENV_NAME}

  # Customise the testing environment
  # ---------------------------------
  - conda install --quiet --file conda-requirements.txt
  - pip install imagehash

  # Summerise environment
  # ---------------------
  - conda list
  - conda info -a

script: python run_test.py
